"""added error_message field in files table

Revision ID: 4e346fb4a6a6
Revises: 64f908ac0a42
Create Date: 2025-12-08 00:06:33.642262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e346fb4a6a6'
down_revision: Union[str, None] = '64f908ac0a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if ingestion failed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'error_message')
    # ### end Alembic commands ###
