"""Add conversation and message models

Revision ID: 98e38db6f59c
Revises: d3a39aca57a1
Create Date: 2025-12-07 13:03:08.220691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98e38db6f59c'
down_revision: Union[str, None] = 'd3a39aca57a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique conversation identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when conversation was started'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique message identifier'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Foreign key to conversation'),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role_enum'), nullable=False, comment='Message role: user or assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message text content'),
    sa.Column('file_id', sa.UUID(), nullable=True, comment='Optional reference to PDF file attached to this message'),
    sa.Column('retrieval_mode', sa.Enum('INLINE', 'RAG', name='retrieval_mode_enum'), nullable=True, comment='How assistant retrieved information (null for user messages)'),
    sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array of retrieved chunks (null for inline or user messages)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when message was sent'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_file_id'), 'messages', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_file_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
