"""Create files table

Revision ID: d3a39aca57a1
Revises: 
Create Date: 2025-12-06 19:13:30.755176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a39aca57a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique file identifier'),
    sa.Column('s3_key', sa.String(length=255), nullable=False, comment='S3 object key (e.g., uploads/{uuid}.pdf)'),
    sa.Column('ingestion_status', sa.Enum('UPLOADED', 'COMPLETED', 'FAILED', name='ingestion_status_enum'), nullable=False, comment='Processing status: uploaded, processing, completed, failed'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when file was uploaded'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when file was last modified'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
